public enum CarOptionsEnum {
    LEATHER_SEATS,
    SUNROOF,
    HEATED_SEATS,
    BACKUP_CAMERA,
    NAVIGATION_SYSTEM,
    BLUETOOTH,
    REMOTE_START,
    BLIND_SPOT_MONITORING,
    CLIMATE_CONTROL
}
